apiVersion: v1
kind: Pod
metadata:
  name: verect-build-test
spec:
  imagePullSecrets:
    - name: acr-secret
  containers:
    - name: verect-backend
      image: builderserver12.azurecr.io/verect-backend:latest
      env:
        - name: PROJECT_ID
          value: "test-123"
        - name: GIT_REPOSITORY_URL
          value: "https://github.com/verma-garv/vercel"
      envFrom:
        - secretRef:
            name: verect-secrets
  restartPolicy: Never
