apiVersion: batch/v1
kind: Job
metadata:
  name: verect-build-test
spec:
  backoffLimit: 3   # Retry up to 3 times if fails
  # ttlSecondsAfterFinished: 300   Auto-delete Job 300 seconds after completion or failed
  template:
    spec:
      imagePullSecrets:
        - name: "ghcr-secret"
      containers:
        - name: verect-backend
          image: ghcr.io/sharma-jayprakash/verect-backend:latest
          env:
            - name: PROJECT_ID
              value: "test-123"
            - name: GIT_REPOSITORY_URL
              value: "https://github.com/verma-garv/vercel"
          envFrom:
            - secretRef:
                name: verect-secrets
      restartPolicy: Never

